spring:
  datasource:
    url: jdbc:mysql://172.20.1.5:3306/pc_soa_parcial?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

memcache:
  ip: ${IP:172.20.1.6}
  port: 11211

auth:
  url: http://172.20.1.11:8080
